spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petclinic
    username: root
    password: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update